---
title: 'fp-ts로 Typescript 함수형 프로그래밍 시작하기 0'
date: 2021-04-20 00:00:04
category: 'TypeScript'
draft: true
---

본 포스트는 fp-ts 공식문서의 [Learning Resources](https://gcanti.github.io/fp-ts/learning-resources/)에 있는 Getting Started에서 소개하는 문서들을 번역하며 학습한 문서입니다. 원본 문서는 [링크](https://dev.to/gcanti/interoperability-with-non-functional-code-using-fp-ts-432e)에서 확인할 수 있으며 작성한 코드들은 [여기](https://github.com/alstn2468/getting-started-fp-ts/tree/main/src/0_interoperability)에서 확인할 수 있습니다.

## fp-ts를 이용한 비함수형 코드와의 상호 운용성

때로는 함수형 프로그래밍 스타일로 작성되지 않은 코드와 상호 운영해야하는 경우가 있습니다. 그러한 상황에서 fp-ts를 이용해 해결하는 방법을 살펴보겠습니다.

## Sentinels

- 유스 케이스: 실패할 수 있고 코드 도메인의 특수한 값을 반환할 수 있는 API
- 예시: `Array.prototype.findIndex`
- 해결 방법: `Option`

```typescript
import { Option, none, some } from 'fp-ts/Option';

function findIndex<A>(
  as: Array<A>,
  predicate: (a: A) => boolean
): Option<number> {
  const index = as.findIndex(predicate);
  return index === -1 ? none : some(index);
}
```

## `undefined`와 `null`

- 유스 케이스: 실패하고 `undefined`나 `null`을 반환할 수 있는 API
- 예시: `Array.prototype.find`
- 해결 방법: `Option`, `fromNullable`

```typescript
import { Option, fromNullable } from 'fp-ts/Option';

export function find<A>(as: Array<A>, predicate: (a: A) => boolean): Option<A> {
  return fromNullable(as.find(predicate));
}
```

### `find`함수 테스트하기

`Array.prototype`에 있는 `find` 함수는 `null`이나 `undefined`와 같은 Falsy값을 반환할 수 있습니다.

`fromNullable` 함수를 이용해 `find` 함수를 감싸 `Option` 타입을 반환하는 함수로 만들었습니다.

작성한 `find` 함수를 테스트하기 위한 라이브러리는 아래와 같습니다.

- `find` 함수를 테스트하기 위한 라이브러리

```typescript
import { find } from './find';
import * as N from 'fp-ts/number';
import { isSome, none, some, getEq, Option, isNone } from 'fp-ts/lib/Option';
```

- `find` 함수를 테스트하는 코드

새로 작성한 `find` 함수는 값을 찾았을 경우 `some` 태그를 갖는 값을 반환합니다. 값을 찾았을 경우에는 `isSome` 메서드가 `true`를 반환하는지 확인하고 값이 `some`으로 감싸진 값과 같은지 확인합니다.

반면에 값을 찾지 못했을 경우 `none` 태그를 값는 값을 반환합니다. 값을 찾지 못했을 경우에는 `isNone` 메서드가 `true`를 반환하는지 확인하고 값이 `none`과 같은지 확인합니다.

```typescript
describe('find함수 테스트 (undefined와 null)', () => {
  let array: number[] = [1, 2, 3, 5];
  let result: Option<number>;
  const E = getEq(N.Eq);

  it('find함수가 존재하는 값을 찾았을 경우', () => {
    result = find(array, a => a === 1);
    expect(isSome(result)).toBeTruthy();
    expect(E.equals(result, some(1))).toBeTruthy();
  });

  it('find함수가 값을 찾지 못했을 경우', () => {
    result = find(array, a => a === 4);
    expect(isNone(result)).toBeTruthy();
    expect(E.equals(result, none)).toBeTruthy();
  });
});
```

## 예외

- 유즈 케이스: `throw`될 수 있는 API
- 예시: `JSON.parse`
- 해결 방법: `Eiter`, `tryCatch`

```typescript
import { Either, tryCatch } from 'fp-ts/Either';

function parse(s: string): Either<Error, unknown> {
  return tryCatch(
    () => JSON.parse(s),
    reason => new Error(String(reason))
  );
}
```

## 무작위 값

- 유즈 케이스: 비결정론적인 값을 반환하는 API
- 예시: `Math.random`
- 해결 방법: `IO`

```typescript
import { IO } from 'fp-ts/IO';

const random: IO<number> = () => Math.random();
```

## 동기 부수 효과

- 유즈 케이스: 전역 상태를 읽거나 쓰는 API
- 예시: `localStorage.getItem`
- 해결 방법: `IO`

```typescript
import { Option, fromNullable } from 'fp-ts/Option';
import { IO } from 'fp-ts/IO';

function getItem(key: string): IO<Option<string>> {
  return () => fromNullable(localStorage.getItem(key));
}
```

- 유즈 케이스: 전역 상태를 읽고 / 쓰고 `throw`할 수있는 API
- 예시: `readFileSync`
- 해결 방법: `IOEither`, `tryCatch`

```typescript
import * as fs from 'fs';
import { IOEither, tryCatch } from 'fp-ts/IOEither';

function readFileSync(path: string): IOEither<Error, string> {
  return tryCatch(
    () => fs.readFileSync(path, 'utf8'),
    reason => new Error(String(reason))
  );
}
```

## 비동기 부수 효과

- 유즈 케이스: 비동기 계산을 수행하는 API
- 예시: 표준 입력으로부터 읽을 때
- 해결 방법: `Task`

```typescript
import { createInterface } from 'readline';
import { Task } from 'fp-ts/Task';

const read: Task<string> = () =>
  new Promise<string>(resolve => {
    const rl = createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    rl.question('', answer => {
      rl.close();
      resolve(answer);
    });
  });
```

- 유즈 케이스: 비동기 계산을 수행하고 거부될 수 있는 API
- 예시: 표준 `fetch`
- 해결 방법: `TaskEither`, `tryCatch`

```typescript
import { TaskEither, tryCatch } from 'fp-ts/TaskEither';

function get(url: string): TaskEither<Error, string> {
  return tryCatch(
    () => fetch(url).then(res => res.text()),
    reason => new Error(String(reason))
  );
}
```
